#!/bin/sh

BASE_DIR=/srv/ks/conveyor
TEMPLATE_NAME=${1}

KS_COMMANDS=${BASE_DIR}/templates/${TEMPLATE_NAME}/commands
KS_PACKAGES=${BASE_DIR}/templates/${TEMPLATE_NAME}/packages
KS_PRE=${BASE_DIR}/templates/${TEMPLATE_NAME}/pre
KS_POST=${BASE_DIR}/templates/${TEMPLATE_NAME}/post
KS_POST_HEADER=${BASE_DIR}/templates/${TEMPLATE_NAME}/post.header
PACKAGES_OPTS=${PACKAGES_OPTS:-"--nobase"}
IGNORE_DIRS="RCS"

my_cat(){
  if [ -f "$1" ] 
   then
    cat ${1}
   else
    if [ ${1##*/} != "RCS" ]
     then
       for i in ${1}/*
        do
         cat ${i}
        done
    fi
  fi
}

echo "## AUTO GENERATED by conveyor assembly line" 
cd ${KS_COMMANDS} 
for cmd in * 
 do
  my_cat ${cmd}
 done

echo
echo "%packages $PACKAGES_OPTS"
cd ${KS_PACKAGES}
for pkg in * 
 do
  my_cat ${pkg}
 done
echo "%end"

echo
cd ${KS_PRE}
for pre in *
 do
  echo "%pre"
  my_cat ${pre}
  echo "%end"
 done

echo
cd ${KS_POST}
for post in *
 do
  echo "%post --erroronfail --log=/root/anaconda-${post}.log"
  for h in ${KS_POST_HEADER}/* 
   do
    my_cat ${h}
   done
  my_cat ${post}
  echo "%end"
 done

