#!/usr/in/python

"""Assemble Kickstart from reusable pieces
FS structure:

BASE_DIR/
  parts
    commands/
      comm1
      comm2
    packages/
      pkg1
      pkg2
    pre/
      pre1
      pre2
    post/
      post1
      post2
    post.header/
      header1
  templates/
    templateA/
      commands/
        comm1 -> ../../parts/commands/comm1
      packages/
        pkg2 -> ../../parts/packages/pkg2
      pre/
        pre1 -> ../../parts/pre/pre1
      post/
        post1 -> ../../parts/post/post1
      post.header/
        header1 -> ../../parts/post.header/header1
     templateB/
      ...

"""

from __future__ import print_function
import sys
import argparse
import os
import os.path

## BASE_DIR='/srv/ks/conveyor'

def cat(filename,ignore_dirs,preamble="",ps=""):
    if os.path.isfile(filename):
        if preamble:
            print(preamble)
        f=open(filename,'r')
        print(f.read())
        f.close()
        if ps:
            print(ps)
    elif os.path.isdir(filename):
        if not (os.path.basename(filename) in ignore_dirs):
            for fn in os.listdir(filename):
                if preamble:
                    print(preamble)
                f=open(os.path.join(filename,fn),'r')
                print(f.read())
                f.close()
                if ps:
                    print(ps)
        
class Assembler(object):
    _base_dir=None
    def __init__(self,base_dir):
        self._base_dir=base_dir

    def assemble(self,template_id,pkg_opts,ignore_dirs):
        template_dir=os.path.join(self._base_dir,'templates',template_id)
        ks_commands=os.path.join(template_dir,'commands')
        ks_packages=os.path.join(template_dir,'packages')
        ks_pre=os.path.join(template_dir,'pre')
        ks_post=os.path.join(template_dir,'post')
        ks_post_header=os.path.join(template_dir,'post.header')

        print("## Auto-generated by conveyor line")
        cat(ks_commands,ignore_dirs)

        print("\n%packages "+pkg_opts)
        cat(ks_packages,ignore_dirs)
        print("%end\n")

        cat(ks_pre,ignore_dirs,preamble='%pre',ps='%end')

        cat(ks_post,ignore_dirs,preamble='%post --erroronfail',ps='%end')

if __name__ == '__main__':
    parser=argparse.ArgumentParser()

    parser.add_argument('--base-dir','-b',type=str,help='',default='.')
    subparsers=parser.add_subparsers(dest='command',help='')

    parser_assemble=subparsers.add_parser('assemble')
    parser_assemble.add_argument('--template-id','-t',type=str,help='',required=True,default=None)
    parser_assemble.add_argument('--packages-opts','-o',type=str,help='',default='--nobase')
    parser_assemble.add_argument('--ignore-dirs','-i',type=str,help='',default='RCS')

    args=parser.parse_args(sys.argv[1:])
    if args.command == 'assemble':
        a=Assembler(args.base_dir)
        a.assemble(args.template_id,args.packages_opts,args.ignore_dirs)

